import client from "./client"

export async function getSectorWeightings(ticker: string) {
    const response = await client.get<SectorWeightings[]>(`/api/v3/etf-sector-weightings/${ticker}`)
    return response.data
}
// Generated by https://quicktype.io

export interface SectorWeightings {
    sector:           string;
    weightPercentage: string;
}
